//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamerary.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Account
    {
        public int accountID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string birthdate { get; set; }
        public string userAddress { get; set; }
        public string phoneNumber { get; set; }
        [Required(ErrorMessage = "E-mail girmek zorundasınız!")]
        public string eMail { get; set; }
        [Required(ErrorMessage = "Şifre girmek zorundasınız!")]
        public string passwrd { get; set; }
        public Nullable<int> uAccountID { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
