//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamerary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameList
    {
        public int gameListID { get; set; }
        public Nullable<int> uAccountID { get; set; }
        public Nullable<int> gameID { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
