//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamerary.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserAccount()
        {
            this.Accounts = new HashSet<Account>();
            this.GameLists = new HashSet<GameList>();
        }

        public int uAccountID { get; set; }
        [Required(ErrorMessage = "İsim girmek zorundasınız!")]
        public string uFirstName { get; set; }
        [Required(ErrorMessage = "Soy isim girmek zorundasınız!")]
        public string uLastName { get; set; }
        [Required(ErrorMessage = "Tarih girmek zorundasınız!")]
        [Display(Name = "releaseDate")]
        [DataType(DataType.Date)]
        public string uBirthdate { get; set; }
        public string uUserAddress { get; set; }
        [Required(ErrorMessage = "Telefon numarası girmek zorundasınız!")]
        [Display(Name = "Home Phone")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Telefon numarası geçersiz, başında 0 olmadan 10 haneli olacak şekilde giriniz!")]
        public string uPhoneNumber { get; set; }
        [Required(ErrorMessage = "E-mail girmek zorundasınız!")]
        [EmailAddress(ErrorMessage = "Geçerli bir E-mail giriniz!")]
        public string uEMail { get; set; }
        [Required(ErrorMessage = "Şifre girmek zorundasınız!")]
        public string uPasswrd { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameList> GameLists { get; set; }
    }
}
